[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "hugo --gc"
  publish = "public"
  functions = "./functions"

[context.deploy-preview]
  command = "npm run build:preview"
  functions = "./functions"
